language: c
dist: trusty

sudo: required

services:
  - docker

matrix:
  include:
    - os: osx
      env: TYPE=osx
    - os: linux
      env: TYPE=ubuntu-17.10
    - os: linux
      env: TYPE=debian-buster
    - os: linux
      env: TYPE=centos-7
    - os: linux
      env: TYPE=ubuntu-16.04
  allow_failures:
    - os: linux
      env: TYPE=ubuntu-16.04

install:
  - source ./travis/install-deps

script:
  - bash ./travis/run-tests
