language: c
dist: trusty

sudo: required

services:
  - docker

matrix:
  include:
    - env: TYPE=ubuntu-17.10
    - env: TYPE=debian-buster
    - env: TYPE=centos-7
    - env: TYPE=ubuntu-16.04
  allow_failures:
    - env: TYPE=ubuntu-16.04

install:
  - docker build
      -t ocaml-gi/${TYPE}
      -f travis/Dockerfile.${TYPE}
      .

script:
  - docker run
      --interactive
      --tty
      ocaml-gi/${TYPE}
